### ISSUE TITLE
Pipeline model_training not working independently

### ISSUE THREAD

**Issue by karol-kuczmarz** [Jakub-Kucinski/kedro-image-classification#12]
When trying to run:
```
kedro run --pipeline model_training
```
we get an error:
```
ValueError: Pipeline input(s) {'train_loader', 'test_loader'} not found in the DataCatalog
```

**Comment by karol-kuczmarz** [comment]
Irrelevant. Everything is working

**Comment by Talha345** [comment]
Hi,I am having the same issue.Unable to run model_training pipeline independently.

Steps to reproduce:

1. Clone the project, create conda env and install dependencies.
2. Run` kedro run --pipeline data_download`
3. Run `kedro run --pipeline data_processing`
4. Run `kedro run --pipeline model_training`

Error:

```
ValueError: Pipeline input(s) {'test_loader', 'train_loader'} not found in theDataCatalog
```

**Comment by Jakub-Kucinski** [comment]
Model training pipeline requires some inputs that are not stored in data catalog, which causes the ValueError you encountered. To address that I added model_training and model_evaluation tags. Now you can run those pipelines using
`kedro run --tags model_training` and `kedro run --tags model_evaluation`. I also updated README.md accordingly.
