### ISSUE TITLE
Use `env` in kedro

### ISSUE THREAD

**Issue by rnoxy** [Jakub-Kucinski/kedro-image-classification#2]
Please consider using `--env ` parameter for running kedro pipelines.

Your case 
```
# from torchvision
kedro run --pipeline data_download --params=download_options.source:torchvision
# from AWS S3 bucket (require previous AWS access configuration)
kedro run --pipeline data_download --params=download_options.source:aws
```

looks like you should create `conf/aws/*` for AWS environment
You can keep default `cond/base/*` for torchvision

**Comment by Jakub-Kucinski** [comment]
Thank you for your advice. Based on that I added custom download envs for AWS and Torchvision in `conf/download_confs` folder and appropriately updated README. [Link to the commit.](https://github.com/Jakub-Kucinski/kedro-image-classification/commit/cfc9318c6ad8d3e55d637f4a4d306a4488e228b8)
